const orderList = [
  {
    id: "1",
    createdAt: "2024-01-01 7:40PM",
    restaurantId: "1",
    itemIds: ["1", 2, 3],
    deliveredAt: "2024-01-01 8:15PM",
    deliveryRating: 4.0,
    foodRating: 4.0,
    deliveredBy: "1",
    addressId: "1",
    paymentId: "1",
    status: "Delivered",
  },
  {
    id: "1",
    createdAt: "2024-01-01 7:40PM",
    restaurantId: "1",
    itemIds: ["1", 2, 3],
    deliveredAt: "2024-01-01 8:15PM",
    deliveryRating: 4.0,
    foodRating: 4.0,
    deliveredBy: "1",
    addressId: "1",
    paymentId: "1",
    status: "Cancelled",
  },
  {
    id: "1",
    createdAt: "2024-01-01 7:40PM",
    restaurantId: "1",
    itemIds: ["1", 2, 3],
    deliveredAt: "",
    deliveryRating: "",
    foodRating: "",
    deliveredBy: "",
    addressId: "1",
    paymentId: "1",
    status: "On-Time",
  },
];

export default orderList;
